language: python
python:
  - "3.7"

git:
  depth: false

before_install:
    - pip install -r requirements.txt
    - wget -O /tmp/gommit https://github.com/antham/gommit/releases/download/v2.2.0/gommit_linux_386
    - chmod 777 /tmp/gommit
jobs:
  include:
    - name: "Check commits"
      script: perl test-branch-commit-messages-in-travis.pl
    - name: "Unit tests"
      script: make test
    - name: "Code coverage"
      script: make cov
      after_success:
        - codecov
    - name: "Linter"
      script: make lint
branches:
  only:
  - master
  - develop